---
- hosts: test_server
  tasks:
   - name: Create directory
     become: yes
     ansible.builtin.file:
      path: /home/ansible/tmp
      state: directory
      owner: kudoushota
      mode: "0755"

   - name: Copy file
     ansible.builtin.copy:
      src: /etc/hosts
      dest: /home/ansible/tmp/hosts
      owner: kudoushota
      mode: "0644"

   - name: Get Kernel information
     ansible.builtin.command:
      cmd: uname -r
     register: result

   - name: Check
     ansible.builtin.debug:
      var: result 

         
   - name: Debug IP address
     ansible.builtin.debug:
      msg: "{{ ansible_facts.default_ipv4.address }}" 
