--- 
- hosts: all
  tasks: 
   - name: Install the Chrony in Redhat
     ansible.builtin.dnf:
      name: chrony
      state: present
     when: ansible_facts['os_family'] == 'Redhat'
     
    
   - name: Install the Chrony in Debian
     become: yes
     ansible.builtin.apt:
      name: chrony
      state: present
     when: ansible_facts['os_family'] == 'Debian'
  
   - name: Install the httpd for web_servers
     ansible.builtin.dnf: 
      name: httpd
      state: installed
     when: host_role == 'web'

   - name: Install the mysql for db_servers
     ansible.builtin.dnf: 
      name: mysql
      state: installed
     when: host_role == 'db'
